name: Helm

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: kube-the-home/github-actions/.github/workflows/helm-lint.yaml@fe98580ed98ea0175f4f491114fe3ac5b83177ca # v1.1.1
    with:
      chart_path: charts/aspire-dashboard
