name: Helm

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: kube-the-home/github-actions/.github/workflows/helm-lint.yaml@8278f5cff77f1f2a90c367c6fa9726e27cbc5612 # v1.3.3
    with:
      chart_path: charts/aspire-dashboard
