name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: kube-the-home/github-actions/.github/workflows/semantic-release.yaml@84c1860e25ca085e075b72749337455d6b3ed16c # v1.3.0
    secrets:
      APP_ID: ${{ secrets.RELEASE_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.RELEASE_APP_PEM }}

  helm:
    needs: release
    if: needs.release.outputs.new_version != ''
    uses: kube-the-home/github-actions/.github/workflows/helm-release.yaml@84c1860e25ca085e075b72749337455d6b3ed16c # v1.3.0
    with:
      chart_path: charts/aspire-dashboard
      version: ${{ needs.release.outputs.new_version }}
      helm_dependency_repos: |
        opentelemetry-collector https://open-telemetry.github.io/opentelemetry-helm-charts
    secrets:
      APP_ID: ${{ secrets.RELEASE_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.RELEASE_APP_PEM }}
