name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: kube-the-home/github-actions/.github/workflows/semantic-release.yaml@b67640d904b560a3a20f5cb94e6ddd5bfa955d65 # v1.4.10
    secrets:
      APP_ID: ${{ secrets.RELEASE_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.RELEASE_APP_PEM }}

  helm:
    needs: release
    if: needs.release.outputs.new_version != ''
    uses: kube-the-home/github-actions/.github/workflows/helm-release.yaml@b67640d904b560a3a20f5cb94e6ddd5bfa955d65 # v1.4.10
    with:
      chart_path: charts/aspire-dashboard
      version: ${{ needs.release.outputs.new_version }}
      helm_dependency_repos: |
        opentelemetry-collector https://open-telemetry.github.io/opentelemetry-helm-charts
    secrets:
      APP_ID: ${{ secrets.RELEASE_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.RELEASE_APP_PEM }}
