name: Conventional Commits

on:
  pull_request:
    branches:
      - main

jobs:
  conventions:
    uses: kube-the-home/github-actions/.github/workflows/git-conventions.yaml@8278f5cff77f1f2a90c367c6fa9726e27cbc5612 # v1.3.3
